# Generated by Django 3.2.7 on 2021-12-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20211225_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='countr',
            new_name='country',
        ),
    ]
