# Generated by Django 3.2.7 on 2021-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_order_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.IntegerField(max_length=10),
        ),
    ]
