# Generated by Django 3.2.7 on 2021-12-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_auto_20211225_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(max_length=500),
        ),
    ]
